### ISSUE TITLE
Make the Destination search bar a drop down

### ISSUE THREAD

**Issue by Asimov4** [Asimov4/icare#1]
As a user, I need a dropdown for the list of ski destinations I might want to go to, so that I take less time to search for an itinerary.

**Comment by Asimov4** [comment]
@sarahbrace I will need the list of destinations to add as dropdown options to make this ticket happen.

**Comment by sarahbrace** [comment]
Here you go!

Crystal Mountain 
Stevens Pass
Snoqualmie Pass
Mount Baker

**Comment by Asimov4** [comment]
The destination is now a dropdown in the demo app:
![image](https://user-images.githubusercontent.com/897911/87238557-b5d11a00-c3b8-11ea-8035-3b688dff97d3.png)
