### ISSUE TITLE
Modify the language on the landing page

### ISSUE THREAD

**Issue by sarahbrace** [Asimov4/icare#3]
Update the language on the landing page to reflect changes in the attached document.
![feedback on app for Thibaut](https://user-images.githubusercontent.com/67525870/85934606-e170e200-b899-11ea-8607-31a3a312f4c5.png)

**Comment by Asimov4** [comment]
Here we go (with the background image):

![2020-06-28-10-23-snowpool-app herokuapp com](https://user-images.githubusercontent.com/897911/85954032-6d7e1a80-b929-11ea-9de4-70f6d6cf3bed.png)

Closing this ticket.
