### ISSUE TITLE
Changes to "Set up the Route" page

### ISSUE THREAD

**Issue by sarahbrace** [Asimov4/icare#6]
See attached screen shot to adjust two things: 

1. Change header from "Set up the route" to "Driver's Destination" 
2. Remove "Avoid Tolls" and "Avoid Highways" boxes. 
![F4AA0EAD-AA1C-47AB-A06E-FA4BACE6EBCD](https://user-images.githubusercontent.com/67525870/87312357-4bfa6280-c4d5-11ea-8f28-4d8199f2b926.jpeg)

**Comment by Asimov4** [comment]
I fixed both!
